eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka  instance:    hostname: localhost
spring:
  application:
    name: coupon-service
    #moved below properties to config-server
  #datasource:
   # url: jdbc:mysql://localhost:3306/microDemoDb
    #username: root
    #password: root
  #jpa:
   #hibernate:
    #ddl-auto: update  zipkin:    base-url: http://127.0.0.1:9411/
  config:    import:    - optional:configserver:http://localhost:8888  profiles:    active:    - prod 
#@JsonFormat set the date with one day less (while get data, date was becoming -1)  jackson:    time-zone: Asia/Kolkata    locale: en_IN
management:
  endpoints:
    web:
      exposure:
        include: "*" 
        exclude:
          - heapdump