eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka  instance:    hostname: localhost
spring:
  application:
    name: product-service
  datasource:
    url: jdbc:mysql://localhost:3306/microDemoDb
    username: root
    password: root
  jpa:
   hibernate:
    ddl-auto: update
  zipkin:
    base-url: http://127.0.0.1:9411/    
server:
  port: 8082